[package]
name = "game_ava1"
version = "0.1.0"
edition = "2024"

[profile.dev]

opt-level = 0
debug = true

[dependencies]
avian2d = "0.3.0"
bevy = { version = "0.16.0", features = ["dynamic_linking"] }
